# $schema ./schema.json

enum: [ sae, d4, sdd ]
int: [ noop ]
type: [ synthetic-wmpy ]

density:
  n_reals: [ 3, 5 ]
  n_bools: [ 3, 5 ]
  n_clauses: [ 9, 13 ]
  len_clauses: [ 7 ]
  n_queries: [ 0 ]
  p_bool: [ 0.5, 0.6 ]
  depth: [ 3 ]
  v_lbound: [ 0 ]
  v_ubound: [ 1 ]
  d_lbound: [ 0 ]
  d_ubound: [ 3 ]
  c_lbound: [ -10 ]
  c_ubound: [ 10 ]
  max_mono: [ 3 ]
  seed: [ 1, 2, 3 ]
