name: Docker[wmibench]

on:
  push:
    branches: [ "main" ]
    paths: [ "image/wmibench/**" ]
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/docker-publish.yml
    permissions:
      contents: read
      packages: write
    with:
      folder: wmibench
